<a href="https://colab.research.google.com/github/Karthik2830/Karthik2830/blob/main/Implementation_of_seed_operations_using_tensor_flow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.random.set_seed(42)
#print(tf.random.set_seed(1234))
tensor1 = tf.random.normal(shape=(2, 3))
#print(tensor1)
tensor2 = tf.random.normal(shape=(2, 3))
#print(tensor2)
print("Are the two tensors identical?", tf.reduce_all(tensor1 == tensor2))

Are the two tensors identical? tf.Tensor(False, shape=(), dtype=bool)


In [2]:
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
shuffled_tensor = tf.random.shuffle(input_tensor)
print("Shuffled tensor without seed:\n", shuffled_tensor.numpy())

Shuffled tensor without seed:
 [[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [3]:
#with seed
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
tf.random.set_seed(42)
shuffled_tensor = tf.random.shuffle(input_tensor)
print("Shuffled tensor with seed:\n", shuffled_tensor.numpy())

Shuffled tensor with seed:
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]


In [4]:
input_tensor = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8]])
tf.random.set_seed(42)
shuffled_tensor_op_seed = tf.random.shuffle(input_tensor)
tf.random.set_seed(42)
shuffled_tensor_global_seed = tf.random.shuffle(input_tensor)
tf.random.set_seed(42)
shuffled_tensor_global_seed2 = tf.random.shuffle(input_tensor)
print("Shuffled tensor with operation seed:\n", shuffled_tensor_op_seed.numpy())
print("Shuffled tensor with global seed:\n", shuffled_tensor_global_seed.numpy())
print("Shuffled tensor with global seed (second execution):\n", shuffled_tensor_global_seed2.numpy())

Shuffled tensor with operation seed:
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]
Shuffled tensor with global seed:
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]
Shuffled tensor with global seed (second execution):
 [[7 8]
 [1 2]
 [3 4]
 [5 6]]


In [5]:
tf.random.set_seed(42)
tensor1 = tf.random.normal(shape=(2, 3))
tf.random.set_seed(11)
tensor2 = tf.random.normal(shape=(2, 3))
print(tensor1)
print(tensor2)
print("Are the two tensors identical? ", tf.reduce_all(tensor1 == tensor2))
seed = [1, 2]
new_seeds = tf.random.split(seed, num=3)
print(new_seeds)

tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.5229472   0.66954476 -0.6424697 ]
 [ 1.4300429   0.5867822   0.4392982 ]], shape=(2, 3), dtype=float32)
Are the two tensors identical?  tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor(
[[1105988140 1738052849]
 [-335576002  370444179]
 [  10670227 -246211131]], shape=(3, 2), dtype=int32)
